<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuit [
<!ELEMENT circuit
        (circuit*,
	(and|andthree|or|orthree|xor|neg|nand|nor|switch|bulb|label|zero|one|jk|led|clock|nib|wire|abscircuit)*)>
<!ATTLIST circuit
        name CDATA #REQUIRED>
<!ELEMENT and (coords?, parent-of*)>
<!ATTLIST and
        id CDATA #REQUIRED>
<!ELEMENT andthree (coords?, parent-of*)>
<!ATTLIST andthree
        id CDATA #REQUIRED>
<!ELEMENT or (coords?, parent-of*)>
<!ATTLIST or
        id CDATA #REQUIRED>
<!ELEMENT orthree (coords?, parent-of*)>
<!ATTLIST orthree
        id CDATA #REQUIRED>
<!ELEMENT xor (coords?, parent-of*)>
<!ATTLIST xor
        id CDATA #REQUIRED>
<!ELEMENT neg (coords?, parent-of*)>
<!ATTLIST neg
        id CDATA #REQUIRED>
<!ELEMENT nand (coords?, parent-of*)>
<!ATTLIST nand
        id CDATA #REQUIRED>
<!ELEMENT nor (coords?, parent-of*)>
<!ATTLIST nor
        id CDATA #REQUIRED>
<!ELEMENT jk (coords?, parent-of*)>
<!ATTLIST jk
        id CDATA #REQUIRED>
<!ELEMENT led (coords?, parent-of*)>
<!ATTLIST led
        id CDATA #REQUIRED>
<!ELEMENT zero (coords?, parent-of*)>
<!ATTLIST zero
        id CDATA #REQUIRED>
<!ELEMENT one (coords?, parent-of*)>
<!ATTLIST one
        id CDATA #REQUIRED>
<!ELEMENT switch (coords?, parent-of*)>
<!ATTLIST switch
        id CDATA #REQUIRED
        number CDATA #REQUIRED
	label CDATA #IMPLIED>
<!ELEMENT bulb (coords?, parent-of*)>
<!ATTLIST bulb
        id CDATA #REQUIRED
        number CDATA #REQUIRED
	label CDATA #IMPLIED>
<!ELEMENT label (coords?, parent-of*, text)>
<!ATTLIST label
        id CDATA #REQUIRED
	size CDATA #REQUIRED
	style CDATA #REQUIRED
	color CDATA #REQUIRED>
<!ELEMENT text (#PCDATA)>
<!ELEMENT clock (coords?, parent-of*)>
<!ATTLIST clock
        id CDATA #REQUIRED
	speed CDATA #REQUIRED>
<!ELEMENT nib (coords?, parent-of*)>
<!ATTLIST nib
        id CDATA #REQUIRED>
<!ELEMENT wire (coords?, parent-of*)>
<!ATTLIST wire
        id CDATA #REQUIRED
	direction CDATA #REQUIRED>
<!ELEMENT abscircuit (coords?, parent-of*)>
<!ATTLIST abscircuit
        id CDATA #REQUIRED
	base CDATA #REQUIRED>
<!ELEMENT coords EMPTY>
<!ATTLIST coords
	x CDATA #REQUIRED
	y CDATA #REQUIRED>
<!ELEMENT parent-of (#PCDATA)>
<!ATTLIST parent-of
        pindex CDATA #REQUIRED
        cindex CDATA #REQUIRED>]>
<circuit name="hundredled">
   <circuit name="fullled">
      <circuit name="hundredctr">
         <jk id="hundredctr:JK1">
            <coords x="411" y="16"/>
            <parent-of pindex="4" cindex="0">hundredctr:Wire5</parent-of>
         </jk>
         <jk id="hundredctr:JK2">
            <coords x="572" y="108"/>
            <parent-of pindex="4" cindex="0">hundredctr:Wire12</parent-of>
         </jk>
         <jk id="hundredctr:JK3">
            <coords x="762" y="198"/>
            <parent-of pindex="4" cindex="0">hundredctr:Wire14</parent-of>
         </jk>
         <jk id="hundredctr:JK4">
            <coords x="920" y="288"/>
            <parent-of pindex="4" cindex="0">hundredctr:Wire11</parent-of>
         </jk>
         <wire id="hundredctr:Wire1" direction="right">
            <coords x="347" y="331"/>
            <parent-of pindex="1" cindex="0">hundredctr:Wire2</parent-of>
            <parent-of pindex="2" cindex="2">hundredctr:JK4</parent-of>
         </wire>
         <wire id="hundredctr:Wire2" direction="right">
            <coords x="362" y="241"/>
            <parent-of pindex="2" cindex="2">hundredctr:JK3</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Wire3</parent-of>
         </wire>
         <wire id="hundredctr:Wire3" direction="right">
            <coords x="377" y="151"/>
            <parent-of pindex="2" cindex="2">hundredctr:JK2</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Wire4</parent-of>
         </wire>
         <wire id="hundredctr:Wire4" direction="right">
            <coords x="392" y="59"/>
            <parent-of pindex="2" cindex="2">hundredctr:JK1</parent-of>
         </wire>
         <bulb id="hundredctr:Bulb2" number="2" label="a0">
            <coords x="987" y="23"/>
         </bulb>
         <bulb id="hundredctr:Bulb3" number="3" label="a1">
            <coords x="1136" y="116"/>
         </bulb>
         <bulb id="hundredctr:Bulb4" number="4" label="a2">
            <coords x="1113" y="205"/>
         </bulb>
         <bulb id="hundredctr:Bulb5" number="5" label="a3">
            <coords x="1119" y="294"/>
         </bulb>
         <wire id="hundredctr:Wire5" direction="right">
            <coords x="490" y="37"/>
            <parent-of pindex="2" cindex="0">hundredctr:Wire7</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Wire30</parent-of>
         </wire>
         <wire id="hundredctr:Wire7" direction="right">
            <coords x="518" y="37"/>
            <parent-of pindex="2" cindex="0">hundredctr:Wire8</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Wire31</parent-of>
         </wire>
         <wire id="hundredctr:Wire8" direction="right">
            <coords x="564" y="37"/>
            <parent-of pindex="2" cindex="0">hundredctr:Wire9</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Wire28</parent-of>
         </wire>
         <wire id="hundredctr:Wire9" direction="right">
            <coords x="602" y="37"/>
            <parent-of pindex="1" cindex="0">hundredctr:Not1</parent-of>
            <parent-of pindex="2" cindex="0">hundredctr:Wire10</parent-of>
         </wire>
         <neg id="hundredctr:Not1">
            <coords x="491" y="109"/>
            <parent-of pindex="1" cindex="0">hundredctr:Wire26</parent-of>
         </neg>
         <wire id="hundredctr:Wire10" direction="right">
            <coords x="649" y="38"/>
            <parent-of pindex="1" cindex="0">hundredctr:And1</parent-of>
            <parent-of pindex="2" cindex="0">hundredctr:Wire36</parent-of>
         </wire>
         <and id="hundredctr:And1">
            <coords x="699" y="81"/>
            <parent-of pindex="2" cindex="0">hundredctr:Wire24</parent-of>
         </and>
         <wire id="hundredctr:Wire11" direction="right">
            <coords x="1007" y="309"/>
            <parent-of pindex="1" cindex="0">hundredctr:Not2</parent-of>
            <parent-of pindex="2" cindex="0">hundredctr:Wire25</parent-of>
         </wire>
         <neg id="hundredctr:Not2">
            <coords x="1021" y="250"/>
            <parent-of pindex="1" cindex="1">hundredctr:And1</parent-of>
         </neg>
         <wire id="hundredctr:Wire12" direction="right">
            <coords x="720" y="130"/>
            <parent-of pindex="1" cindex="1">hundredctr:And2</parent-of>
            <parent-of pindex="2" cindex="0">hundredctr:Wire35</parent-of>
         </wire>
         <wire id="hundredctr:Wire13" direction="right">
            <coords x="730" y="38"/>
            <parent-of pindex="1" cindex="0">hundredctr:And2</parent-of>
            <parent-of pindex="2" cindex="0">hundredctr:Wire16</parent-of>
         </wire>
         <and id="hundredctr:And2">
            <coords x="788" y="65"/>
            <parent-of pindex="2" cindex="0">hundredctr:Wire23</parent-of>
         </and>
         <andthree id="hundredctr:Andthree1">
            <coords x="896" y="153"/>
            <parent-of pindex="3" cindex="0">hundredctr:Wire17</parent-of>
         </andthree>
         <wire id="hundredctr:Wire14" direction="right">
            <coords x="840" y="219"/>
            <parent-of pindex="1" cindex="2">hundredctr:Andthree1</parent-of>
            <parent-of pindex="2" cindex="0">hundredctr:Wire34</parent-of>
         </wire>
         <wire id="hundredctr:Wire15" direction="right">
            <coords x="845" y="131"/>
            <parent-of pindex="1" cindex="1">hundredctr:Andthree1</parent-of>
            <parent-of pindex="2" cindex="0">hundredctr:Bulb3</parent-of>
         </wire>
         <wire id="hundredctr:Wire16" direction="right">
            <coords x="856" y="38"/>
            <parent-of pindex="1" cindex="0">hundredctr:Andthree1</parent-of>
            <parent-of pindex="2" cindex="0">hundredctr:Bulb2</parent-of>
         </wire>
         <wire id="hundredctr:Wire17" direction="right">
            <coords x="935" y="171"/>
            <parent-of pindex="2" cindex="0">hundredctr:Wire22</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Wire29</parent-of>
         </wire>
         <switch id="hundredctr:Switch0" number="0" label="Cl">
            <coords x="388" y="427"/>
            <parent-of pindex="0" cindex="0">hundredctr:Wire18</parent-of>
         </switch>
         <wire id="hundredctr:Wire18" direction="right">
            <coords x="433" y="347"/>
            <parent-of pindex="2" cindex="3">hundredctr:JK4</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Wire19</parent-of>
         </wire>
         <wire id="hundredctr:Wire19" direction="right">
            <coords x="448" y="257"/>
            <parent-of pindex="2" cindex="3">hundredctr:JK3</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Wire20</parent-of>
         </wire>
         <wire id="hundredctr:Wire20" direction="right">
            <coords x="463" y="167"/>
            <parent-of pindex="2" cindex="3">hundredctr:JK2</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Wire21</parent-of>
         </wire>
         <wire id="hundredctr:Wire21" direction="right">
            <coords x="366" y="75"/>
            <parent-of pindex="2" cindex="3">hundredctr:JK1</parent-of>
         </wire>
         <switch id="hundredctr:Switch1" number="1" label="&gt;">
            <coords x="254" y="316"/>
            <parent-of pindex="0" cindex="0">hundredctr:Wire1</parent-of>
         </switch>
         <bulb id="hundredctr:Bulb6" number="6" label="Turn">
            <coords x="1137" y="393"/>
         </bulb>
         <wire id="hundredctr:Wire22" direction="right">
            <coords x="859" y="299"/>
            <parent-of pindex="2" cindex="0">hundredctr:JK4</parent-of>
         </wire>
         <wire id="hundredctr:Wire23" direction="right">
            <coords x="720" y="209"/>
            <parent-of pindex="2" cindex="0">hundredctr:JK3</parent-of>
         </wire>
         <wire id="hundredctr:Wire24" direction="right">
            <coords x="535" y="119"/>
            <parent-of pindex="2" cindex="0">hundredctr:JK2</parent-of>
         </wire>
         <wire id="hundredctr:Wire25" direction="right">
            <coords x="1050" y="309"/>
            <parent-of pindex="2" cindex="0">hundredctr:Bulb5</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Or4</parent-of>
         </wire>
         <wire id="hundredctr:Wire26" direction="right">
            <coords x="369" y="27"/>
            <parent-of pindex="2" cindex="0">hundredctr:JK1</parent-of>
         </wire>
         <wire id="hundredctr:Wire28" direction="right">
            <coords x="868" y="315"/>
            <parent-of pindex="2" cindex="1">hundredctr:JK4</parent-of>
         </wire>
         <wire id="hundredctr:Wire29" direction="right">
            <coords x="710" y="225"/>
            <parent-of pindex="2" cindex="1">hundredctr:JK3</parent-of>
         </wire>
         <wire id="hundredctr:Wire30" direction="right">
            <coords x="539" y="136"/>
            <parent-of pindex="2" cindex="1">hundredctr:JK2</parent-of>
         </wire>
         <wire id="hundredctr:Wire31" direction="right">
            <coords x="339" y="43"/>
            <parent-of pindex="2" cindex="1">hundredctr:JK1</parent-of>
         </wire>
         <wire id="hundredctr:Wire34" direction="right">
            <coords x="880" y="220"/>
            <parent-of pindex="2" cindex="0">hundredctr:Bulb4</parent-of>
            <parent-of pindex="1" cindex="0">hundredctr:Orthree2</parent-of>
         </wire>
         <wire id="hundredctr:Wire35" direction="right">
            <coords x="787" y="131"/>
            <parent-of pindex="2" cindex="0">hundredctr:Wire15</parent-of>
            <parent-of pindex="1" cindex="1">hundredctr:Orthree2</parent-of>
         </wire>
         <wire id="hundredctr:Wire36" direction="right">
            <coords x="688" y="38"/>
            <parent-of pindex="2" cindex="0">hundredctr:Wire13</parent-of>
            <parent-of pindex="1" cindex="2">hundredctr:Orthree2</parent-of>
         </wire>
         <orthree id="hundredctr:Orthree2">
            <coords x="1027" y="399"/>
            <parent-of pindex="3" cindex="1">hundredctr:Or4</parent-of>
         </orthree>
         <or id="hundredctr:Or4">
            <coords x="1064" y="393"/>
            <parent-of pindex="2" cindex="0">hundredctr:Bulb6</parent-of>
         </or>
      </circuit>
      <circuit name="tenctr">
         <jk id="tenctr:JK1">
            <coords x="411" y="16"/>
            <parent-of pindex="4" cindex="0">tenctr:Wire5</parent-of>
         </jk>
         <jk id="tenctr:JK2">
            <coords x="572" y="108"/>
            <parent-of pindex="4" cindex="0">tenctr:Wire12</parent-of>
         </jk>
         <jk id="tenctr:JK3">
            <coords x="762" y="198"/>
            <parent-of pindex="4" cindex="0">tenctr:Wire14</parent-of>
         </jk>
         <jk id="tenctr:JK4">
            <coords x="920" y="288"/>
            <parent-of pindex="4" cindex="0">tenctr:Wire11</parent-of>
         </jk>
         <wire id="tenctr:Wire1" direction="right">
            <coords x="347" y="331"/>
            <parent-of pindex="2" cindex="2">tenctr:JK4</parent-of>
            <parent-of pindex="1" cindex="0">tenctr:Wire2</parent-of>
         </wire>
         <wire id="tenctr:Wire2" direction="right">
            <coords x="362" y="241"/>
            <parent-of pindex="2" cindex="2">tenctr:JK3</parent-of>
            <parent-of pindex="1" cindex="0">tenctr:Wire3</parent-of>
         </wire>
         <wire id="tenctr:Wire3" direction="right">
            <coords x="377" y="151"/>
            <parent-of pindex="2" cindex="2">tenctr:JK2</parent-of>
            <parent-of pindex="1" cindex="0">tenctr:Wire4</parent-of>
         </wire>
         <wire id="tenctr:Wire4" direction="right">
            <coords x="392" y="59"/>
            <parent-of pindex="2" cindex="2">tenctr:JK1</parent-of>
         </wire>
         <bulb id="tenctr:Bulb2" number="2" label="a0">
            <coords x="987" y="23"/>
         </bulb>
         <bulb id="tenctr:Bulb3" number="3" label="a1">
            <coords x="1136" y="116"/>
         </bulb>
         <bulb id="tenctr:Bulb4" number="4" label="a2">
            <coords x="1113" y="205"/>
         </bulb>
         <bulb id="tenctr:Bulb5" number="5" label="a3">
            <coords x="1124" y="303"/>
         </bulb>
         <wire id="tenctr:Wire5" direction="right">
            <coords x="515" y="37"/>
            <parent-of pindex="1" cindex="1">tenctr:JK1</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Wire7</parent-of>
         </wire>
         <wire id="tenctr:Wire7" direction="right">
            <coords x="518" y="37"/>
            <parent-of pindex="1" cindex="1">tenctr:JK2</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Wire8</parent-of>
         </wire>
         <wire id="tenctr:Wire8" direction="right">
            <coords x="564" y="37"/>
            <parent-of pindex="1" cindex="1">tenctr:JK4</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Wire9</parent-of>
         </wire>
         <wire id="tenctr:Wire9" direction="right">
            <coords x="602" y="37"/>
            <parent-of pindex="1" cindex="0">tenctr:Not1</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Wire10</parent-of>
         </wire>
         <neg id="tenctr:Not1">
            <coords x="486" y="74"/>
            <parent-of pindex="1" cindex="0">tenctr:JK1</parent-of>
         </neg>
         <wire id="tenctr:Wire10" direction="right">
            <coords x="649" y="38"/>
            <parent-of pindex="1" cindex="0">tenctr:And1</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Wire13</parent-of>
         </wire>
         <and id="tenctr:And1">
            <coords x="699" y="81"/>
            <parent-of pindex="2" cindex="0">tenctr:JK2</parent-of>
         </and>
         <wire id="tenctr:Wire11" direction="right">
            <coords x="1007" y="309"/>
            <parent-of pindex="1" cindex="0">tenctr:Not2</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Bulb5</parent-of>
         </wire>
         <neg id="tenctr:Not2">
            <coords x="1021" y="250"/>
            <parent-of pindex="1" cindex="1">tenctr:And1</parent-of>
         </neg>
         <wire id="tenctr:Wire12" direction="right">
            <coords x="722" y="135"/>
            <parent-of pindex="1" cindex="1">tenctr:And2</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Wire15</parent-of>
         </wire>
         <wire id="tenctr:Wire13" direction="right">
            <coords x="730" y="38"/>
            <parent-of pindex="1" cindex="0">tenctr:And2</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Wire16</parent-of>
         </wire>
         <and id="tenctr:And2">
            <coords x="788" y="65"/>
            <parent-of pindex="2" cindex="0">tenctr:JK3</parent-of>
         </and>
         <andthree id="tenctr:Andthree1">
            <coords x="896" y="153"/>
            <parent-of pindex="3" cindex="0">tenctr:Wire17</parent-of>
         </andthree>
         <wire id="tenctr:Wire14" direction="right">
            <coords x="865" y="220"/>
            <parent-of pindex="1" cindex="2">tenctr:Andthree1</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Bulb4</parent-of>
         </wire>
         <wire id="tenctr:Wire15" direction="right">
            <coords x="845" y="131"/>
            <parent-of pindex="1" cindex="1">tenctr:Andthree1</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Bulb3</parent-of>
         </wire>
         <wire id="tenctr:Wire16" direction="right">
            <coords x="856" y="38"/>
            <parent-of pindex="1" cindex="0">tenctr:Andthree1</parent-of>
            <parent-of pindex="2" cindex="0">tenctr:Bulb2</parent-of>
         </wire>
         <wire id="tenctr:Wire17" direction="right">
            <coords x="935" y="171"/>
            <parent-of pindex="2" cindex="0">tenctr:JK4</parent-of>
            <parent-of pindex="1" cindex="1">tenctr:JK3</parent-of>
         </wire>
         <switch id="tenctr:Switch0" number="0" label="Cl">
            <coords x="388" y="420"/>
            <parent-of pindex="0" cindex="0">tenctr:Wire18</parent-of>
         </switch>
         <wire id="tenctr:Wire18" direction="right">
            <coords x="433" y="347"/>
            <parent-of pindex="2" cindex="3">tenctr:JK4</parent-of>
            <parent-of pindex="1" cindex="0">tenctr:Wire19</parent-of>
         </wire>
         <wire id="tenctr:Wire19" direction="right">
            <coords x="448" y="257"/>
            <parent-of pindex="2" cindex="3">tenctr:JK3</parent-of>
            <parent-of pindex="1" cindex="0">tenctr:Wire20</parent-of>
         </wire>
         <wire id="tenctr:Wire20" direction="right">
            <coords x="463" y="167"/>
            <parent-of pindex="2" cindex="3">tenctr:JK2</parent-of>
            <parent-of pindex="1" cindex="0">tenctr:Wire21</parent-of>
         </wire>
         <wire id="tenctr:Wire21" direction="right">
            <coords x="366" y="75"/>
            <parent-of pindex="2" cindex="3">tenctr:JK1</parent-of>
         </wire>
         <switch id="tenctr:Switch1" number="1" label="&gt;">
            <coords x="251" y="316"/>
            <parent-of pindex="0" cindex="0">tenctr:Wire1</parent-of>
         </switch>
      </circuit>
      <circuit name="leddriver">
         <switch id="leddriver:Switch0" number="0" label="i0">
            <coords x="31" y="22"/>
            <parent-of pindex="0" cindex="0">leddriver:Wire8</parent-of>
         </switch>
         <switch id="leddriver:Switch1" number="1" label="i1">
            <coords x="33" y="165"/>
            <parent-of pindex="0" cindex="0">leddriver:Wire11</parent-of>
         </switch>
         <switch id="leddriver:Switch2" number="2" label="i2">
            <coords x="29" y="315"/>
            <parent-of pindex="0" cindex="0">leddriver:Wire6</parent-of>
         </switch>
         <switch id="leddriver:Switch3" number="3" label="i3">
            <coords x="28" y="528"/>
            <parent-of pindex="0" cindex="0">leddriver:Wire12</parent-of>
         </switch>
         <bulb id="leddriver:Bulb4" number="4" label="A">
            <coords x="642" y="37"/>
         </bulb>
         <wire id="leddriver:Wire6" direction="right">
            <coords x="84" y="330"/>
            <parent-of pindex="1" cindex="0">leddriver:Not20</parent-of>
            <parent-of pindex="2" cindex="0">leddriver:Wire23</parent-of>
         </wire>
         <wire id="leddriver:Wire8" direction="right">
            <coords x="80" y="35"/>
            <parent-of pindex="1" cindex="0">leddriver:Not18</parent-of>
            <parent-of pindex="2" cindex="0">leddriver:Wire21</parent-of>
         </wire>
         <bulb id="leddriver:Bulb5" number="5" label="B">
            <coords x="644" y="85"/>
         </bulb>
         <neg id="leddriver:Not18">
            <coords x="95" y="70"/>
            <parent-of pindex="1" cindex="0">leddriver:Wire13</parent-of>
         </neg>
         <wire id="leddriver:Wire11" direction="right">
            <coords x="79" y="180"/>
            <parent-of pindex="1" cindex="0">leddriver:Not19</parent-of>
            <parent-of pindex="2" cindex="0">leddriver:Wire24</parent-of>
         </wire>
         <neg id="leddriver:Not19">
            <coords x="94" y="235"/>
            <parent-of pindex="1" cindex="0">leddriver:Wire14</parent-of>
         </neg>
         <neg id="leddriver:Not20">
            <coords x="99" y="360"/>
            <parent-of pindex="1" cindex="0">leddriver:Wire15</parent-of>
         </neg>
         <neg id="leddriver:Not21">
            <coords x="102" y="573"/>
            <parent-of pindex="1" cindex="0">leddriver:Wire16</parent-of>
         </neg>
         <wire id="leddriver:Wire12" direction="right">
            <coords x="87" y="543"/>
            <parent-of pindex="1" cindex="0">leddriver:Not21</parent-of>
            <parent-of pindex="2" cindex="0">leddriver:Wire22</parent-of>
         </wire>
         <wire id="leddriver:Wire13" direction="right">
            <coords x="145" y="85"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire17</parent-of>
            <parent-of pindex="1" cindex="0">leddriver:Andthree12</parent-of>
         </wire>
         <wire id="leddriver:Wire14" direction="right">
            <coords x="144" y="250"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire18</parent-of>
            <parent-of pindex="1" cindex="0">leddriver:Andthree11</parent-of>
         </wire>
         <wire id="leddriver:Wire15" direction="right">
            <coords x="134" y="375"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire19</parent-of>
            <parent-of pindex="1" cindex="2">leddriver:Andthree12</parent-of>
         </wire>
         <wire id="leddriver:Wire16" direction="right">
            <coords x="147" y="588"/>
            <parent-of pindex="1" cindex="2">leddriver:Andthree11</parent-of>
            <parent-of pindex="2" cindex="2">leddriver:Andthree21</parent-of>
         </wire>
         <wire id="leddriver:Wire17" direction="right">
            <coords x="184" y="85"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire32</parent-of>
            <parent-of pindex="1" cindex="0">leddriver:Andthree18</parent-of>
         </wire>
         <wire id="leddriver:Wire18" direction="right">
            <coords x="179" y="250"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire30</parent-of>
            <parent-of pindex="1" cindex="1">leddriver:Andthree19</parent-of>
         </wire>
         <wire id="leddriver:Wire19" direction="right">
            <coords x="187" y="375"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire36</parent-of>
            <parent-of pindex="1" cindex="1">leddriver:Andthree11</parent-of>
         </wire>
         <wire id="leddriver:Wire21" direction="right">
            <coords x="105" y="35"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire26</parent-of>
            <parent-of pindex="1" cindex="0">leddriver:And18</parent-of>
         </wire>
         <wire id="leddriver:Wire22" direction="right">
            <coords x="132" y="543"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire28</parent-of>
         </wire>
         <wire id="leddriver:Wire23" direction="right">
            <coords x="134" y="330"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire27</parent-of>
            <parent-of pindex="1" cindex="2">leddriver:Andthree13</parent-of>
         </wire>
         <wire id="leddriver:Wire24" direction="right">
            <coords x="141" y="180"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire29</parent-of>
            <parent-of pindex="1" cindex="1">leddriver:Andthree12</parent-of>
         </wire>
         <xor id="leddriver:Xor6">
            <coords x="380" y="27"/>
            <parent-of pindex="2" cindex="0">leddriver:Not22</parent-of>
         </xor>
         <neg id="leddriver:Not22">
            <coords x="442" y="27"/>
            <parent-of pindex="1" cindex="0">leddriver:Orthree7</parent-of>
         </neg>
         <orthree id="leddriver:Orthree7">
            <coords x="507" y="37"/>
            <parent-of pindex="3" cindex="0">leddriver:Bulb4</parent-of>
         </orthree>
         <wire id="leddriver:Wire26" direction="right">
            <coords x="133" y="35"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire60</parent-of>
            <parent-of pindex="1" cindex="0">leddriver:Andthree10</parent-of>
         </wire>
         <wire id="leddriver:Wire27" direction="right">
            <coords x="168" y="330"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire33</parent-of>
            <parent-of pindex="1" cindex="2">leddriver:Andthree19</parent-of>
         </wire>
         <wire id="leddriver:Wire28" direction="right">
            <coords x="160" y="543"/>
            <parent-of pindex="2" cindex="2">leddriver:Orthree7</parent-of>
            <parent-of pindex="1" cindex="1">leddriver:And25</parent-of>
         </wire>
         <wire id="leddriver:Wire29" direction="right">
            <coords x="178" y="180"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire58</parent-of>
         </wire>
         <wire id="leddriver:Wire30" direction="right">
            <coords x="220" y="250"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire34</parent-of>
         </wire>
         <wire id="leddriver:Wire32" direction="right">
            <coords x="224" y="85"/>
            <parent-of pindex="1" cindex="0">leddriver:And25</parent-of>
            <parent-of pindex="2" cindex="0">leddriver:Wire85</parent-of>
         </wire>
         <wire id="leddriver:Wire33" direction="right">
            <coords x="198" y="330"/>
            <parent-of pindex="1" cindex="1">leddriver:Xor6</parent-of>
            <parent-of pindex="2" cindex="0">leddriver:Wire74</parent-of>
         </wire>
         <wire id="leddriver:Wire34" direction="right">
            <coords x="287" y="250"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire37</parent-of>
         </wire>
         <wire id="leddriver:Wire36" direction="right">
            <coords x="231" y="375"/>
            <parent-of pindex="1" cindex="2">leddriver:Andthree10</parent-of>
            <parent-of pindex="2" cindex="1">leddriver:Andthree21</parent-of>
         </wire>
         <wire id="leddriver:Wire37" direction="right">
            <coords x="343" y="250"/>
            <parent-of pindex="1" cindex="0">leddriver:Andthree21</parent-of>
            <parent-of pindex="2" cindex="1">leddriver:Andthree23</parent-of>
         </wire>
         <bulb id="leddriver:Bulb6" number="6" label="C">
            <coords x="645" y="153"/>
         </bulb>
         <bulb id="leddriver:Bulb7" number="7" label="D">
            <coords x="651" y="237"/>
         </bulb>
         <bulb id="leddriver:Bulb8" number="8" label="E">
            <coords x="649" y="308"/>
         </bulb>
         <bulb id="leddriver:Bulb9" number="9" label="F">
            <coords x="644" y="388"/>
         </bulb>
         <bulb id="leddriver:Bulb10" number="10" label="G">
            <coords x="647" y="480"/>
         </bulb>
         <neg id="leddriver:Not23">
            <coords x="590" y="388"/>
            <parent-of pindex="1" cindex="0">leddriver:Bulb9</parent-of>
         </neg>
         <andthree id="leddriver:Andthree10">
            <coords x="278" y="281"/>
            <parent-of pindex="3" cindex="0">leddriver:Orthree11</parent-of>
         </andthree>
         <andthree id="leddriver:Andthree11">
            <coords x="270" y="503"/>
            <parent-of pindex="3" cindex="1">leddriver:And18</parent-of>
         </andthree>
         <and id="leddriver:And18">
            <coords x="304" y="477"/>
            <parent-of pindex="2" cindex="0">leddriver:Wire83</parent-of>
         </and>
         <andthree id="leddriver:Andthree12">
            <coords x="298" y="406"/>
            <parent-of pindex="3" cindex="0">leddriver:Wire84</parent-of>
         </andthree>
         <andthree id="leddriver:Andthree13">
            <coords x="336" y="215"/>
            <parent-of pindex="3" cindex="0">leddriver:Wire82</parent-of>
         </andthree>
         <orthree id="leddriver:Orthree11">
            <coords x="377" y="358"/>
            <parent-of pindex="3" cindex="1">leddriver:Or9</parent-of>
         </orthree>